name: Criar e Publicar Release com Arquivos

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # Adicionamos permissões para a action poder criar uma release
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar pasta de destino e copiar arquivos
        run: |
          mkdir flat-files
          find . -type f -not -path './.git/*' -not -path './.github/*' -exec cp --backup=numbered {} flat-files/ \;

      - name: Compactar arquivos em um ZIP
        run: zip -r arquivos-achatados.zip ./flat-files

      - name: Criar Release e fazer upload do ZIP
        uses: softprops/action-gh-release@v2
        with:
          # O nome do arquivo que será anexado à release
          files: arquivos-achatados.zip
          # Cria uma tag única baseada na data e hora para cada release
          # Ex: release-2023-10-27-14-30-05
          tag_name: release-${{ github.run_id }}
          name: "Arquivos Achatados (Build ${{ github.run_id }})"
          body: |
            Download de todos os arquivos do repositório em uma única pasta.
            Executado em: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
