name: Limpar Repositório

on:
  workflow_dispatch:
    inputs:
      preservar:
        description: 'Arquivos/pastas adicionais a preservar (separados por espaço)'
        required: false
        default: ''
        type: string

permissions:
  contents: write

jobs:
  limpeza:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Listar arquivos antes da remoção
        run: ls -la

      - name: Preparar lista de exclusões
        run: |
          # Criar arquivo temporário com padrões a preservar
          echo ".github" > .preservar
          echo ".git" >> .preservar
          
          # Adicionar os padrões fornecidos pelo usuário
          if [ ! -z "${{ github.event.inputs.preservar }}" ]; then
            for item in ${{ github.event.inputs.preservar }}; do
              echo "$item" >> .preservar
              echo "Preservando: $item"
            done
          fi
          
          cat .preservar

      - name: Remover arquivos e pastas (exceto os especificados)
        run: |
          # Remover tudo exceto os padrões listados em .preservar
          while IFS= read -r pattern; do
            find_args="$find_args -not -name \"$pattern\" -not -path \"./$pattern/*\""
          done < .preservar
          
          eval "find . -mindepth 1 -maxdepth 1 $find_args -exec rm -rf {} +"

      - name: Listar arquivos após a remoção
        run: ls -la

      - name: Commit e push das mudanças
        run: |
          git add .
          git commit -m "Limpeza manual do repositório (preservando itens especificados)" || echo "Nenhuma mudança para commitar"
          git push origin HEAD --force
